#!/bin/bash

# 색상 정의
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=======================================${NC}"
echo -e "${GREEN}    CampStation 환경 설정 스크립트    ${NC}"
echo -e "${BLUE}=======================================${NC}"

# .env 파일 생성 확인
if [ -f .env ]; then
    echo "기존 .env 파일이 존재합니다."
    read -p "덮어쓰시겠습니까? (y/N): " overwrite
    if [[ $overwrite != "y" && $overwrite != "Y" ]]; then
        echo "설정을 종료합니다."
        exit 0
    fi
fi

# 랜덤 비밀번호 생성 함수
generate_password() {
    openssl rand -hex 16
}

echo ""
echo -e "${BLUE}[1. 기본 설정]${NC}"
read -p "배포 도메인 (예: mycamp.duckdns.org): " DOMAIN_NAME

# 포트 설정 (기본값)
NEXT_PUBLIC_API_URL="https://${DOMAIN_NAME}/api"
AWS_S3_PUBLIC_ENDPOINT="https://${DOMAIN_NAME}/storage"

echo ""
echo -e "${BLUE}[2. 데이터베이스 설정 (자동 생성)]${NC}"
DB_PASSWORD=$(generate_password)
REDIS_PASSWORD=$(generate_password)
echo "DB Password: (generated)"
echo "Redis Password: (generated)"

echo ""
echo -e "${BLUE}[3. 보안 설정 (자동 생성)]${NC}"
JWT_SECRET=$(generate_password)
echo "JWT Secret: (generated)"

echo ""
echo -e "${BLUE}[4. 관리자 계정 설정]${NC}"
read -p "관리자 이메일: " ADMIN_EMAIL
ADMIN_PASSWORD=$(generate_password)
echo "관리자 비밀번호가 자동으로 생성되었습니다: $ADMIN_PASSWORD"
echo "설치 후 이 비밀번호로 로그인해주세요."

echo ""
echo -e "${BLUE}[5. 외부 서비스 API 키 (선택 사항 - Enter 건너뛰기)]${NC}"
read -p "Google Client ID: " GOOGLE_CLIENT_ID
read -p "Google Client Secret: " GOOGLE_CLIENT_SECRET
read -p "Kakao Client ID: " KAKAO_CLIENT_ID
read -p "Kakao Client Secret: " KAKAO_CLIENT_SECRET
read -p "Naver Client ID: " NAVER_CLIENT_ID
read -p "Naver Client Secret: " NAVER_CLIENT_SECRET
read -p "Toss Client Key: " TOSS_CLIENT_KEY
read -p "Toss Secret Key: " TOSS_SECRET_KEY

# .env 파일 작성
cat > .env <<EOL
# Generated by setup-env.sh

# App Settings
NODE_ENV=production
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
INTERNAL_API_URL=http://campstation-backend:8080
NEXT_PUBLIC_APP_NAME=CampStation
NEXT_PUBLIC_APP_VERSION=1.0.0

# Database
DB_URL=jdbc:postgresql://db:5432/campstation
DB_USERNAME=campstation
DB_PASSWORD=${DB_PASSWORD}
DB_POOL_SIZE=20

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASSWORD}

# MinIO (S3)
MINIO_ROOT_USER=campstation
MINIO_ROOT_PASSWORD=${DB_PASSWORD}
AWS_S3_BUCKET_NAME=campstation-prod
AWS_S3_REGION=us-east-1
AWS_S3_ACCESS_KEY_ID=campstation
AWS_S3_SECRET_ACCESS_KEY=${DB_PASSWORD}
AWS_S3_ENDPOINT=http://campstation-minio:9000
AWS_S3_EXTERNAL_ENDPOINT=http://campstation-minio:9000
AWS_S3_PUBLIC_ENDPOINT=${AWS_S3_PUBLIC_ENDPOINT}
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001

# JWT
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION=3600000
JWT_REFRESH_EXPIRATION=604800000

# CORS
CORS_ALLOWED_ORIGINS=https://${DOMAIN_NAME},https://www.${DOMAIN_NAME}

# OAuth2
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}

# Admin
ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_EMAIL=${ADMIN_EMAIL}

# Email
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587

# Toss Payments
TOSS_CLIENT_KEY=${TOSS_CLIENT_KEY}
TOSS_SECRET_KEY=${TOSS_SECRET_KEY}
NEXT_PUBLIC_TOSS_CLIENT_KEY=${TOSS_CLIENT_KEY}

# Frontend keys 
NEXT_PUBLIC_NAVER_MAP_CLIENT_ID=
EOL

echo ""
echo -e "${GREEN}설정 파일(.env) 생성이 완료되었습니다!${NC}"
echo "관리자 비밀번호: ${ADMIN_PASSWORD}"
echo "---------------------------------------"
echo "이제 다음 명령어로 서비스를 실행할 수 있습니다:"
echo "docker compose -f docker-compose.prod.yml up -d --build"
