-- Sample data for blacklists table (20 entries)
-- PostgreSQL compatible SQL

INSERT INTO blacklists (
    id, name, masked_name, age, gender, phone, masked_phone, region, pc_cafe, 
    danger_level, reason, description, reported_by, report_date, status, 
    verified, views, created_at, updated_at
) VALUES
-- Entry 1
(
    gen_random_uuid(),
    '김철수',
    '김**',
    28,
    '남성',
    '010-1234-5678',
    '010-****-5678',
    '서울',
    'PC방 게임존',
    '위험',
    '폭언 및 기물파손',
    '게임 중 욕설을 하고 키보드를 부쉈습니다. 다른 손님들에게 위협적인 행동을 보였습니다.',
    'admin',
    '2024-11-15',
    '승인',
    true,
    245,
    NOW(),
    NOW()
),
-- Entry 2
(
    gen_random_uuid(),
    '이영희',
    '이**',
    32,
    '여성',
    '010-2345-6789',
    '010-****-6789',
    '부산',
    '메가PC방',
    '경고',
    '음식물 반입',
    '여러 차례 주의했음에도 불구하고 냄새나는 음식을 반복적으로 반입했습니다.',
    'user123',
    '2024-11-20',
    '승인',
    true,
    156,
    NOW(),
    NOW()
),
-- Entry 3
(
    gen_random_uuid(),
    '박민수',
    '박**',
    24,
    '남성',
    '010-3456-7890',
    '010-****-7890',
    '대구',
    '스타PC방',
    '위험',
    '미성년자 흡연',
    '화장실에서 흡연하다 적발되었으며, 거짓 신분증을 사용했습니다.',
    'manager01',
    '2024-11-18',
    '승인',
    true,
    312,
    NOW(),
    NOW()
),
-- Entry 4
(
    gen_random_uuid(),
    '최지훈',
    '최**',
    29,
    '남성',
    '010-4567-8901',
    '010-****-8901',
    '인천',
    '레전드PC방',
    '주의',
    '소음 발생',
    '밤 늦은 시간 큰 소리로 통화하며 다른 손님들에게 민폐를 끼쳤습니다.',
    'staff_kim',
    '2024-11-22',
    '검토 중',
    false,
    89,
    NOW(),
    NOW()
),
-- Entry 5
(
    gen_random_uuid(),
    '정수연',
    '정**',
    26,
    '여성',
    '010-5678-9012',
    '010-****-9012',
    '서울',
    '뉴PC방',
    '경고',
    '요금 미납',
    '3시간 사용 후 계산하지 않고 도주했습니다. CCTV에 얼굴이 찍혔습니다.',
    'owner_lee',
    '2024-11-19',
    '승인',
    true,
    198,
    NOW(),
    NOW()
),
-- Entry 6
(
    gen_random_uuid(),
    '강동현',
    '강**',
    31,
    '남성',
    '010-6789-0123',
    '010-****-0123',
    '광주',
    '프로게이머PC방',
    '위험',
    '성희롱',
    '여성 직원에게 반복적으로 성희롱 발언을 했습니다.',
    'admin',
    '2024-11-16',
    '승인',
    true,
    421,
    NOW(),
    NOW()
),
-- Entry 7
(
    gen_random_uuid(),
    '윤서아',
    '윤**',
    22,
    '여성',
    '010-7890-1234',
    '010-****-1234',
    '대전',
    '하이퍼PC방',
    '주의',
    '자리 독점',
    '4인석을 혼자 사용하며 다른 손님들의 이용을 방해했습니다.',
    'manager02',
    '2024-11-21',
    '승인',
    true,
    134,
    NOW(),
    NOW()
),
-- Entry 8
(
    gen_random_uuid(),
    '임태양',
    '임**',
    27,
    '남성',
    '010-8901-2345',
    '010-****-2345',
    '울산',
    '게이밍존PC방',
    '경고',
    '불법 프로그램 사용',
    '게임 핵 프로그램을 사용하다 적발되었습니다.',
    'user456',
    '2024-11-17',
    '승인',
    true,
    267,
    NOW(),
    NOW()
),
-- Entry 9
(
    gen_random_uuid(),
    '한지우',
    '한**',
    25,
    '여성',
    '010-9012-3456',
    '010-****-3456',
    '서울',
    '엘리트PC방',
    '주의',
    '쓰레기 무단 투기',
    '자리에 음료수병과 과자봉지를 그대로 두고 퇴장했습니다.',
    'staff_park',
    '2024-11-23',
    '검토 중',
    false,
    72,
    NOW(),
    NOW()
),
-- Entry 10
(
    gen_random_uuid(),
    '오준혁',
    '오**',
    30,
    '남성',
    '010-0123-4567',
    '010-****-4567',
    '부산',
    '챔피언PC방',
    '위험',
    '음주 및 폭력',
    '술에 취한 상태로 입장하여 다른 손님과 시비가 붙었습니다.',
    'owner_choi',
    '2024-11-14',
    '승인',
    true,
    389,
    NOW(),
    NOW()
),
-- Entry 11
(
    gen_random_uuid(),
    '신민재',
    '신**',
    23,
    '남성',
    '010-1357-2468',
    '010-****-2468',
    '경기',
    '킹PC방',
    '경고',
    '장비 파손',
    '마우스를 던져서 모니터를 파손했습니다.',
    'manager03',
    '2024-11-20',
    '승인',
    true,
    223,
    NOW(),
    NOW()
),
-- Entry 12
(
    gen_random_uuid(),
    '배수진',
    '배**',
    28,
    '여성',
    '010-2468-1357',
    '010-****-1357',
    '서울',
    '프리미엄PC방',
    '주의',
    '흡연구역 외 흡연',
    '일반 좌석에서 전자담배를 피우다 적발되었습니다.',
    'staff_jung',
    '2024-11-22',
    '승인',
    true,
    145,
    NOW(),
    NOW()
),
-- Entry 13
(
    gen_random_uuid(),
    '류현우',
    '류**',
    26,
    '남성',
    '010-3690-2581',
    '010-****-2581',
    '대구',
    '에이스PC방',
    '위험',
    '절도',
    '다른 손님의 핸드폰을 훔쳐가다 CCTV에 찍혔습니다.',
    'admin',
    '2024-11-15',
    '승인',
    true,
    512,
    NOW(),
    NOW()
),
-- Entry 14
(
    gen_random_uuid(),
    '홍유진',
    '홍**',
    24,
    '여성',
    '010-1470-2580',
    '010-****-2580',
    '인천',
    '로얄PC방',
    '경고',
    '시설물 훼손',
    '화장실 거울에 낙서를 했습니다.',
    'user789',
    '2024-11-19',
    '승인',
    true,
    178,
    NOW(),
    NOW()
),
-- Entry 15
(
    gen_random_uuid(),
    '송재민',
    '송**',
    29,
    '남성',
    '010-9630-7410',
    '010-****-7410',
    '광주',
    '마스터PC방',
    '주의',
    '과도한 음성채팅',
    '새벽 시간 큰 소리로 게임 음성채팅을 하여 민원이 발생했습니다.',
    'manager04',
    '2024-11-21',
    '검토 중',
    false,
    95,
    NOW(),
    NOW()
),
-- Entry 16
(
    gen_random_uuid(),
    '노지훈',
    '노**',
    27,
    '남성',
    '010-7530-9510',
    '010-****-9510',
    '대전',
    '드림PC방',
    '경고',
    '욕설 및 비매너',
    '게임 중 다른 손님들에게 심한 욕설을 했습니다.',
    'staff_lee',
    '2024-11-18',
    '승인',
    true,
    234,
    NOW(),
    NOW()
),
-- Entry 17
(
    gen_random_uuid(),
    '문서현',
    '문**',
    25,
    '여성',
    '010-1593-5740',
    '010-****-5740',
    '울산',
    '슈퍼PC방',
    '주의',
    '좌석 이동 무단',
    '다른 손님의 좌석을 무단으로 사용했습니다.',
    'owner_kim',
    '2024-11-22',
    '승인',
    true,
    112,
    NOW(),
    NOW()
),
-- Entry 18
(
    gen_random_uuid(),
    '표민호',
    '표**',
    31,
    '남성',
    '010-3570-1590',
    '010-****-1590',
    '서울',
    '탑PC방',
    '위험',
    '도박 행위',
    'PC방 내에서 불법 도박 사이트를 이용했습니다.',
    'admin',
    '2024-11-16',
    '승인',
    true,
    456,
    NOW(),
    NOW()
),
-- Entry 19
(
    gen_random_uuid(),
    '석지원',
    '석**',
    23,
    '여성',
    '010-7890-3570',
    '010-****-3570',
    '부산',
    '플래티넘PC방',
    '경고',
    '무단 음식 배달',
    '허가받지 않고 배달음식을 주문하여 받았습니다.',
    'manager05',
    '2024-11-20',
    '승인',
    true,
    189,
    NOW(),
    NOW()
),
-- Entry 20
(
    gen_random_uuid(),
    '진수호',
    '진**',
    28,
    '남성',
    '010-2580-3690',
    '010-****-3690',
    '경기',
    '베스트PC방',
    '주의',
    '자리 예약 후 미사용',
    '여러 자리를 예약해놓고 사용하지 않아 다른 손님의 이용을 방해했습니다.',
    'staff_choi',
    '2024-11-23',
    '검토 중',
    false,
    67,
    NOW(),
    NOW()
);

-- Sample data for blacklist_images table (some entries have images)
INSERT INTO blacklist_images (id, blacklist_id, image_url, created_at)
SELECT 
    gen_random_uuid(),
    b.id,
    CASE 
        WHEN random() < 0.5 THEN 'https://storage.example.com/blacklist/' || b.id || '/evidence1.jpg'
        ELSE 'https://storage.example.com/blacklist/' || b.id || '/evidence2.jpg'
    END,
    NOW()
FROM blacklists b
WHERE b.danger_level IN ('위험', '경고')
LIMIT 15;

-- Verify data
SELECT COUNT(*) as total_blacklists FROM blacklists;
SELECT COUNT(*) as total_images FROM blacklist_images;
SELECT danger_level, COUNT(*) as count FROM blacklists GROUP BY danger_level;
